function R= Periodicity3(r)
L=4; %size of box
r= mod(r,L); %Put all points back inside the unit box

rr = r; %copy of box to the right
rr(:,1) = r(:,1) + L;
rl = r; %copy of box to the left
rl(:,1) = r(:,1) - L;
ru = r; %copy of box above
ru(:,2) = r(:,2)+ L;
rul = ru; %copy of box above to the left
rul(:,1) = ru(:,1) - L;
rur = ru; %copy of box above to the right
rur(:,1) = ru(:,1) + L;
rb = r; %copy of box below
rb(:,2) = r(:,2) - L; 
rbl = rb; %copy of box below to the left
rbl(:,1) = rb(:,1) - L;
rbr = rb; %copy of box below to the right
rbr(:,1) = rb(:,1) + L;
R = vertcat(r,rr,rl); %combine the coordinates together in one vector
R = vertcat(R,ru, rul, rur, rb, rbr, rbl);
R=unique(R,'rows','stable');